services:
  api:
    restart: unless-stopped
    image: comments-api:latest
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - ${API_PORT}:3000
    environment:
      # Frontend Configuration
      - FRONTEND_URL=${FRONTEND_URL}
      # Google Storage
      - GCS_PROJECT_ID=${GCS_PROJECT_ID}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - GCS_KEY_FILE_CONTENT=${GCS_KEY_FILE_CONTENT}
      # Database Configuration
      - DATABASE_URL=${DATABASE_URL}
      # reCAPTCHA Configuration
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
    networks:
      - monorepo_net
    depends_on:
      postgres:
        condition: service_healthy

  web:
    restart: unless-stopped
    image: comments-web:latest
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - ${WEB_PORT}:80
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_RECAPTCHA_SITE_KEY=${VITE_RECAPTCHA_SITE_KEY}
    networks:
      - monorepo_net

  postgres:
    restart: unless-stopped
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monorepo_net
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  monorepo_net:
    driver: bridge

volumes:
  postgres_data:
